name: Publish
on:
  push:
    branches: ["main"]

  schedule:
    - cron: '0 */6 * * *'  # rebuild every 6 hours

  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - name: Fetch map data from RealityMod
        env:
          MAPS_GITHUB_TOKEN: ${{ secrets.MAPS_GITHUB_TOKEN }}
        run: ruby _scripts/fetch_maps.rb
      - uses: jeffreytse/jekyll-deploy-action@v0.6.0
        with:
          provider: 'github'
          token: ${{ secrets.GITHUB_TOKEN }}
          cname: 'bf3reality.com'
